baseURL = "https://erikrios.github.io/"
title = "Erik Rio Setiawan"
theme = "pargo"

googleAnalytics = "UA-########-#"
disqusShortname = "erikrios"

[permalinks]
  post = "/blog/:slug/"
  page = "/:slug/"

[params]
    # Site Author
    author = "Erik Rio Setiawan"

    # Description/subtitle for homepage
    description = "Hello, saya Erik. Blog ini belum jadi. Sabar ya..."

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = [":git", "lastmod", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    wight = 1
  [[menu.main]]
    identifier = "email"
    name = "Email"
    url = "mailto:erikrio.16061@gmail.com"
    wight = 2
  [[menu.main]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/erikriosetiawan"
    wight = 3
  [[menu.main]]
    identifier = "github"
    name = "Github"
    url = "https://github.com/erikrios"
    wight = 4
  [[menu.main]]
    identifier = "rss"
    name = "RSS"
    url = "http://feeds.feedburner.com/erikrios"
    wight = 5